### PR TITLE
Use IconLoader from darklaf from group icons

### PR DESCRIPTION
**Pull request by tychobrailleur**
A few things here:

- I had to cherry pick some changes from master to be able to test this PR – hopefully this will merge back ok into master,
- I have been having an issue with opacity in darklaf, so for now I have got around the issue by creating a second SVG with opacity – I'll need to investigate deeper to create a repro,
- The group icons seem to have an issue with Nimbus (even before the PR):

Screenshot 2020-06-24 at 23 53 05

I think I have also come your way regarding the `GroupTeam` class, i have changed a few things there, but I think you were right segregating that logic (feel free to change my changes if they don't suit you ;-) )

### CODE REVIEW

**Comment by weisJ** [comment]
> * I have been having an issue with opacity in darklaf, so for now I have got around the issue by creating a second SVG with opacity – I'll need to investigate deeper to create a repro,

You have to declare that the color you are defining has opacity set or otherwise it will be overridden. Maybe I should add support for constant opacity values, so they are kept when applying colours.

The syntax is the following:
````xml
<linearGradient id="fillColor" opacity="opacityKey">
    <stop offset="0" stop-color="#FF0000"/>
</linearGradient>
````
The values is taken from the same map as the colours. Currently opacity values are assumes to be integers (that will be divided by `100`).
Note that the `opacity` property not the `linearGradient` isn’t part of the svg specification and will probably be displayed as an error in editors.

**Comment by tychobrailleur** [comment]
> The syntax is the following:
> 
> ```
> <linearGradient id="fillColor" opacity="opacityKey">
>     <stop offset="0" stop-color="#FF0000"/>
> </linearGradient>
> ```

Yes, this is exactly [what I was doing](https://github.com/yaute74/HO/pull/1/files#diff-83e99460e68b79021dc8c5cc46e2a03eR48).  Whilst it was working on a simple self-contained example, it would not work in the application itself.  I haven't been able to track down the root cause (despite spending a few hours, a real head-scratcher...), but I am going to experiment, and once I am sure this is not due to something on our side, I'll get back to you @weisJ .

It seems to be an issue in the svgSalamander loading, I wonder if it's possibly due to the fact that `opacity` is not a valid attribute on `linearGradient`.

Another thing I was going to bring up with you is the opportunity of a more flexible approach to define the opacity, as for now you need to set the value as part of the `UIManager` (cf. https://github.com/yaute74/HO/pull/1/files#diff-83e99460e68b79021dc8c5cc46e2a03eR49), similar to how colours are set in the colour map.  I might hazard a PR on darklaf for that, but you probably already have some thoughts around that.

**Comment by weisJ** [comment]
> Another thing I was going to bring up with you is the opportunity of a more flexible approach to define the opacity, as for now you need to set the value as part of the `UIManager` (cf. https://github.com/yaute74/HO/pull/1/files#diff-83e99460e68b79021dc8c5cc46e2a03eR49), similar to how colours are set in the colour map. I might hazard a PR on darklaf for that, but you probably already have some thoughts around that.

Opacity is already taken from the map you pass to `IconLoader#loadSVGIcon`. If using a custom map then values from the `UIManager` are actually ignored right now. Though I think I'll add a check to try to resolve colors from the `UIManager` if they aren't present in the passed property map.

The following should work fine:
````java
final Map<Object, Object> colorMap = Map.of(
    "fillColor", ImageUtilities.getColorFromHex(props.getValue0()),
    "strokeColor", ImageUtilities.getColorFromHex(props.getValue1()),
    "opacityVal". (int) (Float.parseFloat(opacity) * 100)
);
````

I thin the culprit is `Float.valueOf(opacity).intValue()`. `Float#intValue` just casts to an `int` (which for non trivial opacity values will be `0`).

**Comment by yaute74** [comment]
thanks @tychobrailleur

**Pull request merged**
